package com.wx.rxretrofitlibrary.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wx.rxretrofitlibrary.bean.DownBean;

import com.wx.rxretrofitlibrary.dao.DownBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downBeanDaoConfig;

    private final DownBeanDao downBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downBeanDaoConfig = daoConfigMap.get(DownBeanDao.class).clone();
        downBeanDaoConfig.initIdentityScope(type);

        downBeanDao = new DownBeanDao(downBeanDaoConfig, this);

        registerDao(DownBean.class, downBeanDao);
    }
    
    public void clear() {
        downBeanDaoConfig.clearIdentityScope();
    }

    public DownBeanDao getDownBeanDao() {
        return downBeanDao;
    }

}
